### ISSUE TITLE
ScikitClassifier in lime_eval.py

### ISSUE THREAD

**Issue by guydepauw** [cmry/shed#25]
ScikitClassifier in latest version of lime.text is no longer available.

You can import make_pipeline instead

`from sklearn.pipeline import make_pipeline`

and swap the arguments on line 68

`self.c = make_pipeline(vectorizer, classifier)`

[https://github.com/marcotcr/lime/issues/8](url)

**Comment by cmry** [comment]
Fixed it in my local version!
