### ISSUE TITLE
Parameter max_feats in documentation for NGrams, not implemented

### ISSUE THREAD

**Issue by verhoevenben** [cmry/shed#26]
As title says.
Either remove parameter max_feats from documentation of NGrams (in featurizer.py), or implement.

**Comment by cmry** [comment]
fixed in b003766bbcfe91441b0303f71bee3f4e3d1fa503

**Comment by verhoevenben** [comment]
Still referenced in line 120 and 122

**Comment by cmry** [comment]
fixed in 26976581be0cee9870963b8db41d27c58a64698f
