### ISSUE TITLE
Class labels not retrievable in Vectorizer (for two-class problem)

### ISSUE THREAD

**Issue by verhoevenben** [cmry/shed#28]
I wanted to retrieve the feature names and class labels of a Vectorizer object in order to do some feature analysis. After searching a while, I found that the feature names are availabel in the 'hasher' attribute. However, I was unable to retrieve the class labels. I think they're supposed to be in the 'encoder' attribute, but this seems to be by-passed for binary (but also two-class) problems. Yet, in a two-class problem (e.g. male vs. female) you still need to know which of these is 0 and which is 1.

**Comment by cmry** [comment]
The encoder's `inverse_transform` should solve this. See e.g. https://github.com/cmry/omesa/blob/master/front/app.wsgi#L180 .

**Comment by verhoevenben** [comment]
Aha! That makes sense. And it works. I was put on the wrong foot by the looks of vec.encoder which looks like an empty LabelEncoder() instance and I neglected to investigate further. Apologies and thanks for the answer!
